### PR TITLE
Dev 0.02 readmes

### PR DESCRIPTION
**Pull request by jessb0t**
@anaNDClab Requesting check for merging all my admin changes for the version 0.02 release, please!

### CODE REVIEW

**Comment by jessb0t** [comment]
@anaNDClab I also noticed that in one of our prior merges, we had somehow deleted the CHEXI and TEXI files.  So I went back to a commit in GitHub that had them and put those two folders back in order here. :)

**Comment by jessb0t** [comment]
@anaNDClab I checked that all zips could be uploaded to REDCap because I had been adjusting some by extracting from the zips and recompressing, but I had a suspicion that this might not work as expected.  Sure enough, it did not.  So I verified all .zip files we have and corrected as needed.  I also renamed the variables within AMBIRMBI, SIAS6SPS6, EDSHVS, and PANASRTQ to match the new numbering system (unique number for each question on smooshed surveys).

**Review by anaNDClab — APPROVED** [review]
Hey @jessb0t everything looks good. One final question, for sssq the final readme will not include the delta scores correct?

**Comment by jessb0t** [comment]
> Hey @jessb0t everything looks good. One final question, for sssq the final readme will not include the delta scores correct?

Correct!  We decided not to include delta scores for now.  They make the scoring code much more complex and it's not clear whether we will regularly use them.  Per George, we decided to leave it up to individual researchers if they wanted to add this score during their data analyses.

**Pull request merged**
