### PR TITLE
Implemented version sorting, made some changes on how data is managed

### PR DESCRIPTION
**Pull request by blope118**
* Implemented version sorting
* Filter out metadata once for the whole data set, instead of each Subscore object doing it in gen_data()
* Changed how data is passed into gen_data() so each Subscore object only has to deal with relevant data
* Changed looping, instead of looping through Subscore it loops through versions. for example, it goes from adexi_wm, adexi_inh, adexi_b_wm, adexi_b_inh instead of adexi_wm, adexi_b_wm, adexi_inh, adexi_b_inh
* Fixed minor error in the json file (missing bracket at end)

### CODE REVIEW

**Comment by blope118** [comment]
In the description for this pull request I mentioned how I added a missing bracket at end, that is my error I just hadn't pulled the latest data from dev_0.02. I did delete a bracket at the end though, it seems to have an extra one.

**Comment by F-said** [comment]
Nice. Going to implement some automatic testing to this branch to get a reliable means of scoring w/o pinging anyone. Merging in over the weekend.

**Comment by blope118** [comment]
Hey, I implemented that change I mentioned during today's meeting, to take care of the case if a higher version has a lower sre by sorting sre over the current version not all versions.

**Comment by F-said** [comment]
Integrated automatic testing, included some changes from branch dev-feature-reverseScore for bug fixes
image

(reverse-score is not implemented yet)

**Comment by F-said** [comment]
Columns look sorted. Ready to merge

```
adexi_perc_wm_s1_r1_e1,adexi_scrd_wm_s1_r1_e1,adexi_perc_inh_s1_r1_e1,adexi_scrd_inh_s1_r1_e1,adexi_perc_total_s1_r1_e1,adexi_scrd_total_s1_r1_e1,adexi_b_perc_wm_s1_r2_e1,adexi_b_scrd_wm_s1_r2_e1,adexi_b_perc_inh_s1_r2_e1,adexi_b_scrd_inh_s1_r2_e1,adexi_b_perc_total_s1_r2_e1,adexi_b_scrd_total_s1_r2_e1,aq10_perc_agreed_s1_r1_e1,aq10_scrd_agreed_s1_r1_e1,aq10_perc_disagreed_s1_r1_e1,aq10_scrd_disagreed_s1_r1_e1,aq10_perc_total_s1_r1_e1,aq10_scrd_total_s1_r1_e1,aq10_perc_agreed_s1_r2_e1,aq10_scrd_agreed_s1_r2_e1,aq10_perc_disagreed_s1_r2_e1,aq10_scrd_disagreed_s1_r2_e1,aq10_perc_total_s1_r2_e1,aq10_scrd_total_s1_r2_e1,aq10_perc_agreed_s1_r2_e2,aq10_scrd_agreed_s1_r2_e2,aq10_perc_disagreed_s1_r2_e2,aq10_scrd_disagreed_s1_r2_e2,aq10_perc_total_s1_r2_e2,aq10_scrd_total_s1_r2_e2
```

Sort holds out across data. Nice work @blope118 

```
adexi_perc_wm_s1_r1_e1,adexi_scrd_wm_s1_r1_e1,adexi_perc_inh_s1_r1_e1,adexi_scrd_inh_s1_r1_e1,adexi_perc_total_s1_r1_e1,adexi_scrd_total_s1_r1_e1,adexi_perc_wm_s1_r2_e1,adexi_scrd_wm_s1_r2_e1,adexi_perc_inh_s1_r2_e1,adexi_scrd_inh_s1_r2_e1,adexi_perc_total_s1_r2_e1,adexi_scrd_total_s1_r2_e1,adexi_perc_wm_s1_r2_e2,adexi_scrd_wm_s1_r2_e2,adexi_perc_inh_s1_r2_e2,adexi_scrd_inh_s1_r2_e2,adexi_perc_total_s1_r2_e2,adexi_scrd_total_s1_r2_e2,aq10_perc_agreed_s1_r1_e1,aq10_scrd_agreed_s1_r1_e1,aq10_perc_disagreed_s1_r1_e1,aq10_scrd_disagreed_s1_r1_e1,aq10_perc_total_s1_r1_e1,aq10_scrd_total_s1_r1_e1,erq_perc_CogRea_s1_r1_e1,erq_scrd_CogRea_s1_r1_e1,erq_perc_ExpSup_s1_r1_e1,erq_scrd_ExpSup_s1_r1_e1,bfne_perc_total_s1_r1_e1,bfne_scrd_total_s1_r1_e1
```

**Pull request merged**
